### PR TITLE
Fixed install paths on *NIX

### PR DESCRIPTION
**Pull request by fpesari**
Hello, the previous build was hard to configure for packagers. This one uses a CMake module (`GNUInstallDirs`) to standardize it so that it works like most programs out there and the right install paths are automatically chosen. I already tested this both on my local machine and on the Open Build System (openSUSE).

The Mac part might need some fixing, I had to use the `INSTALL_DIR` variable for consistency but the logic should be the same as before.

### CODE REVIEW

**Review by hannesbraun — APPROVED** [review]
Looks good to me. Thank you very much for your contribution!

**Comment by fpesari** [comment]
Thank you for this project! :smile_cat: these plugins are already in the multimedia:proaudio repo for openSUSE, by the way, we can make you a maintainer for the package if you have an OBS account. Due to licensing issues related to the VST2 SDK, we could never really get Airwindows VSTs in our repo (@joboschetti wrote a downloader for them to get around that) and this project I think will benefit many users.

**Comment by hannesbraun** [comment]
You're welcome :)
My OBS username is "hannesbraun" too in case you want to add me as a maintainer.

**Comment by fpesari** [comment]
Done! The package name on multimedia:proaudio is reversed (`lv2-airwindows`) because we are trying to follow the convention `plugin_type-package_name`.

**Pull request merged**
